### ISSUE TITLE
Not able to clear selection or reset calendar

### ISSUE THREAD

**Issue by ssarya** [Kumar-Aakash/ng-material-date-range-picker#16]
Can we add a functionality to clear date range section on clicking a button like below screen

![2024-03-27_11-44-56](https://github.com/Kumar-Aakash/ng-material-date-range-picker/assets/36930619/55c9e91f-308c-4474-a207-e5391221eeb9)

We need to clean input field as well as dates in the calendar as well or we can say resetting the calendar to its default settings.

**Comment by Kumar-Aakash** [comment]
Hi @ssarya  Yeah, I might need to think of a few scenarios around it and get back on this but this can be marked as an enhancement.

I will update here once this is available in the next version. The target should be this week.

Thank you again for using this library. :)

**Comment by Kumar-Aakash** [comment]
This issue PR work is in progress. It should have few more features including the clear selection.

**Comment by tomgruszowski** [comment]
@Kumar-Aakash is there a way to clear the selection programmatically in the current version?

**Comment by Kumar-Aakash** [comment]
@ssarya @tomgruszowski 

you may find clear date range functionality on below version:
V16 : 1.2.10
V17 : 2.2.4

**Comment by ssarya** [comment]
Thanks Aakash
