### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by sebafra** [Kumar-Aakash/ng-material-date-range-picker#29]
Hi, nice plugin.

I want to translate this to spanish.
I made changes in the default-date-options.mjs but I can´t see changes.
Could you help me?

**Comment by Kumar-Aakash** [comment]
Hi @sebafra  Thank you for using this library.

Right now, in built localization is not supported for date pickers but all custom options and presets can be localized and translated.

If you are looking for localizing presets options, here is how you can do that. @sebafra 

I am using "@jsverse/transloco" for project localization and here is the example 

```
import { TRANSLOCO_SCOPE, TranslocoService } from '@jsverse/transloco';

constructor(
    protected transLocoService: TranslocoService,
    @Inject(TRANSLOCO_SCOPE) protected scope,
  ) {}

public translate(key: string, scope = this.scope): Observable<string> {
    return this.transLocoService.selectTranslate(key, {}, scope);
  }
```

Component Code - 

// Presets should be the keys from json files

```
presets.forEach((preset) => {
      this.createAndTranslateOption(preset, defaultOption).subscribe((option) => {
        options.push(option);
      });
    });

private createAndTranslateOption(
    preset: any,
    defaultOption?: string,
  ): Observable<SelectDateOption> {
    const option = new SelectDateOption();
    return this.$translate(preset.label, this.scope).pipe(
      takeUntil(this.stop$),
      map((res) => {
        option.callBackFunction = preset.action;
        option.optionLabel = res;
        // other config you want to pass to date range picker 
      }),
    );
  }
```


Please let me know if it helps.
