### ISSUE TITLE
Changing Month on first calendar is not updating correctly the second calendar

### ISSUE THREAD

**Issue by fpfcarvalho** [Kumar-Aakash/ng-material-date-range-picker#4]
If we select a custom range, and we choose to change Month through the Year View and not the arrows, the second calendar will calculate the selected month + 1 but the table with the days will remain with the initial data.

<img width="714" alt="Captura de ecrã 2024-03-06, às 18 45 47" src="https://github.com/Kumar-Aakash/ng-material-date-range-picker/assets/272719/9f83cc86-d9fc-47c3-9217-a4df11edb14b">

In my opinion, the header of the second calendar shouldn't change and should stay with the previous selected date and not recalculating

**Comment by Kumar-Aakash** [comment]
Hi, @fpfcarvalho Thank you for using the Library and opening the issue.

Based on the use cases we have, we have decided to keep it as functionality where if you change the starting month using the arrow, the subsequent 2nd-month selector goes +1.

It does help primarily in selecting a date range that is always in the future direction from the starting date selected.

If you're still facing issues where the output event date range is not correct, can you please provide me a minimal reproducible issue or a loom, It might help me understand the issue better.

**Comment by Kumar-Aakash** [comment]
Hi @fpfcarvalho Thank you for providing issue video. 

I should be fixing this over the weekend. I will inform here, once done. Thanks

**Comment by Kumar-Aakash** [comment]
@fpfcarvalho  This is tracked here [PR-6](https://github.com/Kumar-Aakash/ng-material-date-range-picker/pull/6)

**Comment by Kumar-Aakash** [comment]
hi @fpfcarvalho 
This issue is fixed in lib version 2.2.1 (for angular 17) and 1.2.7 (for angular 16)

**Comment by Kumar-Aakash** [comment]
Fixed this issue in v2.2.1 via [132f96dd8](https://github.com/Kumar-Aakash/ng-material-date-range-picker/pull/6/commits/132f96dd8ca7cc43cb0c6af13b47c402b3bda832)
