### ISSUE TITLE
Not able to set min and max date

### ISSUE THREAD

**Issue by ssarya** [Kumar-Aakash/ng-material-date-range-picker#5]
Not able to set min and max date on the calendars

**Comment by Kumar-Aakash** [comment]
Hi @ssarya I will be looking into it this week.

@nilesh-kapale Do you think it is because of config change?

**Comment by Kumar-Aakash** [comment]
@ssarya  This is tracker here. [PR-6](https://github.com/Kumar-Aakash/ng-material-date-range-picker/pull/6)

**Comment by Kumar-Aakash** [comment]
Hi @ssarya 
This issue is fixed in lib version  2.2.1 (for angular 17) and 1.2.7 (for angular 16)

**Comment by Kumar-Aakash** [comment]
Fixed this issue in v2.2.1 via [7ea4616171c](https://github.com/Kumar-Aakash/ng-material-date-range-picker/pull/6/commits/7ea4616171c3a2afb8172e2ff8d2ba86cb1857ac)

**Comment by ssarya** [comment]
Thanks
