### ISSUE TITLE
Is it possible to show the selectedDates value by default?

### ISSUE THREAD

**Issue by chrislat** [Kumar-Aakash/ng-material-date-range-picker#8]
It appears that after the component initialises, the initially selected date range is not visible, even if the `selectedDates` option has been provided. Instead it just shows the string `"Date Range"`. 

However, once a new range is selected, the `"Date Range"` string is replaced by the dates that correspond to the selected range. 

Would it be possible to show the dates also in the first case, instead of showing the `"Date Range"` string? 

P.S.: Thank you for the development of this very useful component.

**Comment by Kumar-Aakash** [comment]
Thank you for appreciating this library @chrislat . Sure, I will be looking into it this week. 

Thanks

**Comment by Kumar-Aakash** [comment]
Hi @chrislat,

We have added support to display default text values on version 2.2.2.

You can provide [selectedOptionIndex] = "number" to change default option selected.
If you want to specify the custom range then provide  [selectedOptionIndex] = "9" and [selectedDates]=" instance of   DateRange<Date> which contains start date and end date."
